server:
  port: 8001

spring:
  application:
    name: EUREKA-SERVER

eureka:
  instance:
    hostname: git.heroku.com/nd2k-registry-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
