server:
  port: 8001

spring:
  application:
    name: EUREKA-SERVER

eureka:
  instance:
    hostname: nd2k-registry-server.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
